// PWA manifest — tells the browser this app is installable. When a
// builder taps "Add to Home Screen" on iOS or accepts Chrome's
// install banner on Android, the app launches as a standalone shell
// (no browser chrome) styled with the colors below.
//
// The `name` here is shown on the install confirmation; `short_name`
// is what fits under the home-screen icon — keep ≤ 12 chars.

import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "KeystonePro — project + estimate + draw management",
    short_name: "KeystonePro",
    description:
      "AI-assisted estimating, draw schedule + lender-ready requests, sub coordination, and customer portal — the custom-home builder workflow in one app.",
    start_url: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#f8fafc", // slate-50, matches app shell bg
    theme_color: "#0369a1", // sky-700, matches brand
    icons: [
      {
        src: "/icon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "any",
      },
      {
        // Generated by app/apple-icon.tsx — 180×180 PNG for iOS.
        src: "/apple-icon",
        sizes: "180x180",
        type: "image/png",
        purpose: "any",
      },
    ],
  };
}
